services:
  asf:
    image: justarchi/archisteamfarm
    container_name: asf

    restart: unless-stopped

    environment:
      ASF_UID: "1001"
      DOTNET_BUNDLE_EXTRACT_BASE_DIR: /tmp

    volumes:
      - ${HOME}/ASF/config:/app/config
      - ${HOME}/ASF/logs:/app/logs

    networks:
      - proxy

networks:
  proxy:
    external: true
