services:
  asf:
    image: justarchi/archisteamfarm
    container_name: asf

    restart: unless-stopped

    environment:
      ASF_CRYPTKEY=${ASF_CRYPTKEY:?required}
      ASF_UID: "1001"
      DOTNET_BUNDLE_EXTRACT_BASE_DIR: /tmp

    ports:
      - "127.0.0.1:1242:1242"
      - "[::1]:1242:1242"

    volumes:
      - ${HOME}/ASF/config:/app/config
      - ${HOME}/ASF/logs:/app/logs

    networks:
      - proxy

networks:
  proxy:
    external: true
